"""baseline schema

Revision ID: 6e88584b4849
Revises: 
Create Date: 2026-04-06 02:25:57.539905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '6e88584b4849'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('previous_api_key_hash', sa.String(length=64), nullable=True),
    sa.Column('api_key_grace_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('api_key_revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_api_key_hash'), 'projects', ['api_key_hash'], unique=True)
    op.create_index(op.f('ix_projects_previous_api_key_hash'), 'projects', ['previous_api_key_hash'], unique=True)
    op.create_table('project_alert_destinations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('target_url', sa.String(length=512), nullable=False),
    sa.Column('secret_token', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_destinations_project_active', 'project_alert_destinations', ['project_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_project_alert_destinations_project_id'), 'project_alert_destinations', ['project_id'], unique=False)
    op.create_table('project_alert_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('operator', sa.String(length=10), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notification_cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_alert_rules_project_id'), 'project_alert_rules', ['project_id'], unique=False)
    op.create_table('project_api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_fingerprint', sa.String(length=12), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_api_keys_key_fingerprint'), 'project_api_keys', ['key_fingerprint'], unique=False)
    op.create_index(op.f('ix_project_api_keys_key_hash'), 'project_api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_project_api_keys_project_id'), 'project_api_keys', ['project_id'], unique=False)
    op.create_table('project_budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('monthly_token_limit', sa.Integer(), nullable=True),
    sa.Column('monthly_cost_limit', sa.Float(), nullable=True),
    sa.Column('alert_threshold_percent', sa.Float(), nullable=False),
    sa.Column('hard_stop_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_budgets_project_id'), 'project_budgets', ['project_id'], unique=True)
    op.create_table('traces',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('trace_metadata', sa.JSON(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('span_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_traces_project_created', 'traces', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_traces_project_id'), 'traces', ['project_id'], unique=False)
    op.create_index(op.f('ix_traces_status'), 'traces', ['status'], unique=False)
    op.create_table('curated_labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('exported', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trace_id')
    )
    op.create_index(op.f('ix_curated_labels_label'), 'curated_labels', ['label'], unique=False)
    op.create_table('project_alert_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('destination_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('rule_name', sa.String(length=120), nullable=True),
    sa.Column('metric', sa.String(length=40), nullable=True),
    sa.Column('operator', sa.String(length=10), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['project_alert_destinations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['project_alert_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_events_project_created', 'project_alert_events', ['project_id', 'created_at'], unique=False)
    op.create_index('ix_alert_events_project_rule_created', 'project_alert_events', ['project_id', 'rule_id', 'created_at'], unique=False)
    op.create_index('ix_alert_events_project_type_created', 'project_alert_events', ['project_id', 'event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_project_alert_events_destination_id'), 'project_alert_events', ['destination_id'], unique=False)
    op.create_index(op.f('ix_project_alert_events_event_type'), 'project_alert_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_project_alert_events_project_id'), 'project_alert_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_alert_events_rule_id'), 'project_alert_events', ['rule_id'], unique=False)
    op.create_table('spans',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('span_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('input', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spans_parent_id'), 'spans', ['parent_id'], unique=False)
    op.create_index(op.f('ix_spans_span_type'), 'spans', ['span_type'], unique=False)
    op.create_index(op.f('ix_spans_trace_id'), 'spans', ['trace_id'], unique=False)
    op.create_index('ix_spans_trace_parent', 'spans', ['trace_id', 'parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_spans_trace_parent', table_name='spans')
    op.drop_index(op.f('ix_spans_trace_id'), table_name='spans')
    op.drop_index(op.f('ix_spans_span_type'), table_name='spans')
    op.drop_index(op.f('ix_spans_parent_id'), table_name='spans')
    op.drop_table('spans')
    op.drop_index(op.f('ix_project_alert_events_rule_id'), table_name='project_alert_events')
    op.drop_index(op.f('ix_project_alert_events_project_id'), table_name='project_alert_events')
    op.drop_index(op.f('ix_project_alert_events_event_type'), table_name='project_alert_events')
    op.drop_index(op.f('ix_project_alert_events_destination_id'), table_name='project_alert_events')
    op.drop_index('ix_alert_events_project_type_created', table_name='project_alert_events')
    op.drop_index('ix_alert_events_project_rule_created', table_name='project_alert_events')
    op.drop_index('ix_alert_events_project_created', table_name='project_alert_events')
    op.drop_table('project_alert_events')
    op.drop_index(op.f('ix_curated_labels_label'), table_name='curated_labels')
    op.drop_table('curated_labels')
    op.drop_index(op.f('ix_traces_status'), table_name='traces')
    op.drop_index(op.f('ix_traces_project_id'), table_name='traces')
    op.drop_index('ix_traces_project_created', table_name='traces')
    op.drop_table('traces')
    op.drop_index(op.f('ix_project_budgets_project_id'), table_name='project_budgets')
    op.drop_table('project_budgets')
    op.drop_index(op.f('ix_project_api_keys_project_id'), table_name='project_api_keys')
    op.drop_index(op.f('ix_project_api_keys_key_hash'), table_name='project_api_keys')
    op.drop_index(op.f('ix_project_api_keys_key_fingerprint'), table_name='project_api_keys')
    op.drop_table('project_api_keys')
    op.drop_index(op.f('ix_project_alert_rules_project_id'), table_name='project_alert_rules')
    op.drop_table('project_alert_rules')
    op.drop_index(op.f('ix_project_alert_destinations_project_id'), table_name='project_alert_destinations')
    op.drop_index('ix_alert_destinations_project_active', table_name='project_alert_destinations')
    op.drop_table('project_alert_destinations')
    op.drop_index(op.f('ix_projects_previous_api_key_hash'), table_name='projects')
    op.drop_index(op.f('ix_projects_api_key_hash'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
